### ISSUE TITLE
Listing 11.13 - Misleading yml hierarchy 

### ISSUE THREAD

**Issue by ahmedkhabkhab** [ahmedkhabkhab/api-gateway#1]
In Listing 11.13, 

```
        - id: spa-route
          uri: ${SPA_URL:http://localhost:9004}
          predicates:
            - Path=/,/*.css,/*.js,/favicon.ico
```

needs to be under `spring.cloud.gateway.routes` and not `spring.gateway.routes`
